[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack_api = "0.22"
slack = "0.22"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
